# Generated by Django 5.0.2 on 2024-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_emissions', models.FloatField()),
                ('electricity_emissions', models.FloatField()),
                ('diet_emissions', models.FloatField()),
                ('waste_emissions', models.FloatField()),
                ('screentime_emission', models.FloatField()),
                ('total_emissions', models.FloatField()),
            ],
        ),
    ]
