# Generated by Django 5.0.4 on 2024-05-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonFootprint', '0002_admindatabase_register_result_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='dietary_plan',
            new_name='diet_emissions',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='screentime',
            new_name='screentime_emissions',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='transportation',
            new_name='transportation_emissions',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='waste',
            new_name='waste_emissions',
        ),
    ]
